openapi: 3.0.0
info:
  title: "Symbol Service Project"
  contact:
    name: "Brijesh Bhomkar"
    url:  ""
    email: "Brijesh.Bhomkar@gmail.com"
  description: "Symbol service maintain NSE/BSE symbols"
  version: "1.0.0"
tags:
  - name: Production
    description: Secured Admin-only calls
  - name: Development
    description: Operations available to developers
paths:
  /symbol:
    get:
      tags:
        - Development
      summary: Get Api to return symbol
      operationId: findsymbol
      description: Api to return the symbol
      parameters:
        - in: query
          name: findSymbol
          description: Return symbol if it exist in the system
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Found symbol
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Symbol'
        '400':
          description: bad input parameter

components:
  schemas:
    Symbol:
      type: object
      required:
        - id
        - symbolid
        - symbol
        - exchange
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        symbolid:
          type: integer
          example: 11234
        symbol:
          type: string
          example: symbol like 'SBI'
        exchange:
          type: string
          example: can be nse or bse

